tslint.json

This PR changes two TSLint rules. Namely, `await-promise` and `no-floating-promises`. Also fixes the type for the rule `max-classes-per-file`.

Change promise rules

---

package.json
validateFileNames.js

I wrote this script which will validate file and directory names according to our naming convention.
After we merge this, we will be able to run...
```
node ./node_modules/@hollowverse/common-config/validateFileNames.js
```
...from `hollowverse/hollowverse` and other repos...
The output looks like this
---
I tried to write this script in TypeScript and I was able to run it fine as...
```
./node_modules/.bin/ts-node validateFileNames.ts
```
...but when I moved it to `@hollowverse/common-config` and tried to run it...
```
./node_modules/.bin/ts-node ./node_modules/@hollowverse/common-config/validateFileNames.ts
```
...I kept getting all kinds of errors. I tried using the `-P` flag to set the right `tsconfig.json` and I tried to remove `node_modules` from the excluded paths in …

Script to validate file names

---

.eslintrc.json
README.md
helpers/decryptSecrets.js
helpers/executeCommands.js
helpers/retryCommand.js
helpers/writeEnvFile.js
package.json
tsconfig.json
validateFileNames.js

This PR adds the following new functions, all located in `./helpers`:
* `decryptSecrets`
* `writeEnvFiles`
* `executeCommands`
* `retryCommand`
These are used in deploy scripts of multiple repos (`hollowverse/hollowverse`, `hollowverse/letsEncrypt`, and possibly `hollowverse/hollowbot` in the future).

Add helpers functions used in deploy scripts

---

helpers/executeCommand.js
helpers/executeCommands.js
helpers/executeCommandsInParallel.js

This PR extracts the logic for executing a single command into a separate module, `executeCommand`, and refactors `executeCommands` to use it internally. This is in order to reuse the code in a new helper, `executeCommandsInParallel`, which as the name implies, executes commands concurrently and fails if one command fails. This will help speed up things when building on CI by building the client and server code concurrently.

Add more helpers

---

validateFileNames.js

The path to the node executable may be different between the Linux distributions, but it looks like `/usr/bin/node` is more standard.

Fix node executable path

---

helpers/decryptSecrets.js
helpers/executeCommand.js
helpers/executeCommands.js
helpers/executeCommandsInParallel.js
helpers/retryCommand.js

Instead of resolving with an exit code (and sometimes a synthetic one for JS functions):
* Resolve on success
* Reject on failure
This makes allows us to use native JS try/catch.
Also, fail if a password is `undefined` in `decryptSecrets`.

Rewrite command execution helpers to use JS semantics

---

helpers/createZipFile.js
helpers/executeCommand.js
helpers/writeJsonFile.js
package.json

This function will be used to package the artificats file in order to deploy to Elastic Beanstalk.
Just like the `artifacts: files` section of `buildspec.yml`, this function accepts glob patterns to add files to the output ZIP file, so we just have to copy the patterns we are already using.
This PR also renames `writeJSONFile` to follow the correct naming convention.

Add createZipFile helper function

---

tsconfig.json

According to [node.green](node.green/#ES2016), Node.js has 100% support for ES2016 since 7.5. Since we are using 8.5 across all our containers, and since webpack overrides the target for our client, it is safe to upgrade the compile target of TS to ES2016 so we transpile the scripts we run in Node.js less.

Upgrade compile target to es2016

---

tslint.json

tslint-microsoft-contrib has a rule (`prefer-array-literal`) that enforces using the array literal syntax (`type[]`) to declare array types, which conflicts with a built-in tslint rule that prefers `Array<>` for complex object types.

Resolve conflicting rules for array types

---

tsconfig.json

This is causing a lot of issues in server-side code. The only case where we might need this is for the client, because Webpack knows how to interpret CommonJS exports as default ES imports.

Disable "allowSyntheticDefaultImports"

---

package.json
tsconfig.json

According to [node.green](http://node.green/#ES2017), Node 9.2 is 100% compatible with ES2017.
This is a major version bump because this could be a breaking change, and to avoid problems with yarn. We can gradually upgrade the dependent repositories.

Compile TypeScript to 2017, require Node 9.2

---

package.json
tslint.json

Rationale: https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad
TL;DR:
* Better developer experience:
* auto-import in VS Code
* easier refactoring
* Better tree shaking in some cases
We are already using named exports almost exclusively in [https://github.com/hollowverse/hollowverse](hollowverse/hollowverse), so it makes sense to enforce this rule. Some refactoring may be required though.
This PR also re-enables that JSX boolean props do not have a value (`disabled` is preferred over `disabled={true}`).

Disallow default exports

---

.eslintrc.json
package.json

`eslint-graphql-plugin` expects to find a `.graphqlconfig` file in every project root, even if we are not actually using any GraphQL API in the project. I'll move the configuration back to `hollowverse/hollowverse`.

Remove GraphQL linting

---

package.json
tsconfig.json

With the introduction of TypeScript 2.7, a new option, `esModuleInterop`, was added to `tsconfig.json` which allows both CommonJS and ES modules to imported with the same import style.
Before
```typescript
// Valid, works
import defaultExport from 'esmodule';
import { namedExport } from 'esmodule';
// Invalid, CommonJS modules do not have named exports
import { namedExport } from 'commonjs';
// Invalid, CommonJS modules do not have a "default" export
import defaultExport from 'commonjs';
// Import module "namespace" object, valid, works
import * as namespace from 'commonjs';
namespace.namedExport;
namespace.default;
// Valid syntax if "allowSyntheticImports" is set to true,
// but may cause a runtime error. TypeScript won't try to make the
// import work. It expects that the conversion to …
```

Enable esModuleInterop option

---

package.json
tsconfig.json

`esModuleInterpo` should imply `allowSyntheticDefaultImports`, but that does not seem to be the case.

Force enable allowSyntheticDefaultImports

---

package.json

This fixes CI for `perf-monitor`. `yarn` checks for this and refuses to install a package if it's not compatible with the current Node.js version.

Update "node" engine version

---

package.json

As a transitive dependency, `babel-eslint` should be in `dependencies`, not `devDependencies`.

Fix babel-eslint

---

semanticRelease/.releaserc.json

This PR improves semantic-release by making it generate a rudimentary changelog (as opposed to not having any changelog at all as before), and disabling the celebration and warnings for success and failure events.

Feature: improve semantic-release

---

clown/jest/package.json
clown/typescript/package.json

Having a command named with the same name as a local binary makes it impossible to run the binary with `yarn`:
```
yarn tslint
```
The command `"tslint"` in `"scripts"` always takes precedence over `./node_modules/.bin/tslint`.

Breaking: Rename tslint command to lint-ts, remove color flag from jest command

---

babel/node/.babelrc
clown/babel/package.json
eslint/react/typescript/.eslintrc.json
eslint/typescript/.eslintrc.json

Turns out `@babel/preset-env` does not always include stage 3 proposal, which includes things like optional catch binding syntax and object rest spread. I think it's safe to include stage 3 syntax.

Breaking: upgrade babel packages, include stage-3, update ESLint config for TS 

---

clown/stylelint/.vscode/settings.json
clown/stylelint/package.json
stylelint/.stylelintrc.json

This provides some kind of "type checking" for CSS. CSSTree Validator checks that the values of CSS properties are valid. Adding this plugin also enables immediate feedback in VS Code (provided that the recommended stylelint plugin is installed).

 Breaking: Add CSSTree validator
